// <auto-generated />
using System;
using AltenChallengeApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AltenChallengeApp.Infrastructure.Migrations
{
    [DbContext(typeof(AltenChallengeAppDbContext))]
    partial class AltenChallengeAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AltenChallengeApp.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("CreatedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new { Id = new Guid("4dcd05e1-69c4-49ca-8863-9359858d8ff5"), Address = "Cementvägen 8", City = "Södertälje", Country = "Sweden", CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 982, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), IsDeleted = false, Name = "Kalles Grustransporter AB", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 982, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"), ZipCode = "111 11" },
                        new { Id = new Guid("6d23151a-6904-4154-af0e-f97ae201c89b"), Address = "Balkvägen 12", City = "Stockholm", Country = "Sweden", CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 982, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), IsDeleted = false, Name = "Johans Bulk AB", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 982, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"), ZipCode = "222 22" },
                        new { Id = new Guid("7df039b0-eb98-4415-813a-f930ce3a20c7"), Address = "Budgetvägen 1", City = "Uppsala", Country = "Sweden", CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 982, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), IsDeleted = false, Name = "Haralds Värdetransporter AB", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 982, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"), ZipCode = "333 33" }
                    );
                });

            modelBuilder.Entity("AltenChallengeApp.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("CreatedBy");

                    b.Property<Guid>("CustomerId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("RegistrationNumber");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new { Id = new Guid("cc9d160d-9cb4-43bf-80f5-ef945e619408"), CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 978, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), CustomerId = new Guid("4dcd05e1-69c4-49ca-8863-9359858d8ff5"), IsDeleted = false, RegistrationNumber = "ABC123", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("5c131134-6d49-48f5-ad8d-a2dccf738ce7"), CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), CustomerId = new Guid("4dcd05e1-69c4-49ca-8863-9359858d8ff5"), IsDeleted = false, RegistrationNumber = "DEF456", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("9fa0be73-befe-4584-9aac-81c04605f905"), CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), CustomerId = new Guid("4dcd05e1-69c4-49ca-8863-9359858d8ff5"), IsDeleted = false, RegistrationNumber = "GHI789", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("ed6a27e9-7f20-4bf4-896e-4ce540307a73"), CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), CustomerId = new Guid("6d23151a-6904-4154-af0e-f97ae201c89b"), IsDeleted = false, RegistrationNumber = "JKL012", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("d40f33e3-19f6-4c55-ba5f-28d7a575879f"), CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), CustomerId = new Guid("6d23151a-6904-4154-af0e-f97ae201c89b"), IsDeleted = false, RegistrationNumber = "MNO345      ", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("b38f284c-d6f3-4732-adc1-94dd56b04e62"), CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), CustomerId = new Guid("7df039b0-eb98-4415-813a-f930ce3a20c7"), IsDeleted = false, RegistrationNumber = "PQR678", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("e3131a06-3a3f-4fc8-98b4-ee762ca4af83"), CreatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), CustomerId = new Guid("7df039b0-eb98-4415-813a-f930ce3a20c7"), IsDeleted = false, RegistrationNumber = "STU901", UpdatedAt = new DateTime(2018, 11, 18, 0, 3, 32, 980, DateTimeKind.Local), UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") }
                    );
                });

            modelBuilder.Entity("AltenChallengeApp.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("AltenChallengeApp.Core.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
